server:
  port: 8081
spring:
  datasource:
    # postgres
    # type: com.alibaba.druid.pool.DruidDataSource
    # url: jdbc:postgresql://127.0.0.1:5432/postgres
    # username: postgres
    # password: fanxfan
    # mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/exam??createDatabaseIfNotExist=true
    username: root
    password: fanxfan
    druid:
      active-connections: 100
      connect-timeout: 60000000
      db-type: postgresql
      default-auto-commit: true
      # driver-class-name: org.postgres.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      password: fanxfan
      database: 0
      port: 6379
      timeout: 10s
      jedis:
        pool:
          enabled: true
          max-active: 32
          min-idle: 0
          max-wait: -1
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: false
        show_sql: true
        hbm2ddl:
          auto: update
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
top:
  fanxfan:
    secret:
      private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANyotY9yF3OWM9iSeAzJkkGd3q1zeYM+UPgVO++3ujMwUXKIV0mEzZMfZpb5By9mpeGHf+kSrX76KLtIWdm4Eo1+dUqiGcqJNwlIJPgbB/nRpC/Qyc0CpN12JUwRRVOUW0ESM5enl2SSMvDI9XuMK9/xXgGwpbhbd881WxoxqyZ7AgMBAAECgYAB65dGO/hHnDtam3kJ+3MXY8KoAG+X8cyN7CQNDldDfMcorQESywy9nAdY3FVGAf8C5cVPh5xqP3kSmtWVVyG/hK2Eqjq/XbfqtQ826Eqr+Poxk3KJaetIikynEa+WL24085G1UtMbmCTpsVgLRNJKVPGM1ez3qmPeqglQCfCBgQJBAO8f33NGbquVc0i5I7CPEca3OumD2mTcUeISM3ab5iZr08MebUCNwpmznJN1in3oAs9+u2pmDKk/EZHmmfh6djsCQQDsOzseVPY209EbvAqANNw7B1c3HqjywQH3L6hjAg911rfFSSHI2F6HTnnylo73H0mmya2/YTgtt5ggP6a2U8zBAkEA0rCyoU8dk/FKcnkuCRMGBqDLN5UFiHjXbOm8jnUuhAvdub3FZWuCWwr2mramH+mdEFYJq+XeogD/6h3U7Cp6oQJBALNIeKOag4o003yjB60pcQLznUNd54bk6GL7LmaFx8n8/VejGxrc61DxRCfSEAqJGlKUuWKHnCVGMxQ2eoXhr4ECQA5pmvvJmcj1P/ebk4jWAT49uFSy7+TU4adVxIsU4Gi/rlCselxUtElJSjF5H7geJNR/i69VHTNTGlrCgM/hcb8=
      public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDcqLWPchdzljPYkngMyZJBnd6tc3mDPlD4FTvvt7ozMFFyiFdJhM2TH2aW+QcvZqXhh3/pEq1++ii7SFnZuBKNfnVKohnKiTcJSCT4Gwf50aQv0MnNAqTddiVMEUVTlFtBEjOXp5dkkjLwyPV7jCvf8V4BsKW4W3fPNVsaMasmewIDAQAB
    captcha:
      enable: false
      type: GIF
      width: 200
      height: 50
      length: 8
      count: 10
# Sa-Token 配置
sa-token:
  token-name: fanxfan
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  alone-redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: fanxfan
    timeout: 10s

logging:
  level:
    top.fanxfan: debug

redis:
  limit:
    key: default
    burst-capacity: 50
    timeout: 120
    rate-interval: seconds
    limit-type: ip
    rate-type: overall
