apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-server-deployment
  labels:
    app: exam-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exam-server
  template:
    metadata:
      name: exam-server
      labels:
        app: exam-server
    spec:
      automountServiceAccountToken: false
      containers:
        - name: exam-server
          image: exam-server
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: "2"
              memory: 2G
      restartPolicy: Always
      