### 验证码获取
GET http://127.0.0.1:8081/auth/code


### 登录
POST http://127.0.0.1:8081/auth
Content-Type: application/json

{
  "account": "fanxfan",
  "password": "123456",
  "type": 0
}

### 获取用户信息
GET http://127.0.0.1:8081/user/list?pageNumber=0&pageSize=20